sudo apt-get update
echo "###########################################"
echo "#"
echo "# 	apt-get database has been updated."
echo "# 	Base de datos de apt-get actualizada."
echo "#"
echo "###########################################"
sudo apt-get upgrade
echo "###########################################"
echo "#"
echo "# 	System applications have been upgraded."
echo "# 	Aplicaciones del sistema actualizadas."
echo "#"
echo "###########################################"
echo ""
echo "###########################################"
echo "#"
echo "# 	End of program."
echo "# 	Fin del programa."
echo "#"
echo "###########################################"
read pause
